{
 "title": "npmGraf Python Dashboard",
 "tags": [
  "npmGraf",
  "Python"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_NPMGRAF", "label": "Data Source", "query": "influxdb" },
   {
    "name": "domainquery",
    "label": "Domain",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"Domain\"\r\n)"
    }
   },
   {
    "name": "domainquery_exclude",
    "label": "Domain Exclude",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"Domain\"\r\n)"
    }
   },
   {
    "name": "statuscodequery",
    "label": "Status Code",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"Statuscode\"\r\n)"
    }
   },
   {
    "name": "ipquery",
    "label": "IP",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"Ip\"\r\n)"
    }
   },
   {
    "name": "ipquery_exclude",
    "label": "IP Exclude",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"Ip\"\r\n)"
    }
   },
   {
    "name": "measurementquery",
    "label": "Measurement",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"_measurement\"\r\n)"
    }
   },
   {
    "name": "agentquery",
    "label": "Agent",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"Agent\"\r\n)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Info Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Code",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"statuscode\")\r\n  |> filter(fn: (r) => r.Statuscode != \"200\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> yield(name: \"alias\")\r\n"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"statuscode\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> yield(name: \"alias\")"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"statuscode\")\r\n  |> filter(fn: (r) => r._value == \"500\")\r\n  |> group(columns: [])\r\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Status 403",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"statuscode\")\r\n  |> filter(fn: (r) => r._value == \"403\")\r\n  |> group(columns: [])\r\n  |> count(column: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Status 404",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"statuscode\")\r\n  |> filter(fn: (r) => r._value == \"404\")\r\n  |> group(columns: [])\r\n  |> count(column: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"agent\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> yield(name: \"alias\")"
    }
   ]
  },
  {
   "title": "Scheme",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"scheme\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> yield(name: \"alias\")"
    }
   ]
  },
  {
   "title": "Method",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"method\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> yield(name: \"alias\")"
    }
   ]
  },
  {
   "title": "AbuseIpDB Confidence Score",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"abuse_confidence_score\")\n  |> group(columns: [\"_measurement\", \"Abuse_Confidence_Score\"])\n  |> count()\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Data (lenght) transmitted per Domain (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"length\")\n  |> group(columns: [\"Domain\"])\n  |> sum()\n  |> group()\n  |> sort(desc: true)\n  |> limit(n: 10)\n  "
    }
   ]
  },
  {
   "title": "Real Connections (without monitoring services or internal calls)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "All real Accessed Domains",
   "type": "bargauge",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per IP",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ip\")  \r\n  |> group(columns: [\"Ip\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit's in the last ...",
   "type": "stat",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"ip\")\r\n  |> group(columns: [\"_count\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per Nation",
   "type": "bargauge",
   "description": "(without monitoring services or internal calls)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"name\")\r\n  |> group(columns: [\"Name\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hits per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"domain\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"_time=1m\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n  |> yield(name: \"count\")",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Redirection Domains",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Reverse Proxy Domains",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "domain" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "World Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Real IPs Map Overview (without excluded IPs)",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "IP" ], "type": "tag" }
     ],
     "measurement": "ReverseProxyConnections",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"ip\")  \r\n  |> group(columns: [\"Longitude\",\"Latitude\",\"Ip\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])",
     "select": [
      [
       { "params": [ "IP" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "counts" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "ASN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "ASN",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"asn\")\r\n  |> group(columns: [\"Asn\", \"Ip\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")"
    }
   ]
  },
  {
   "title": "ASN (per IP)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\" or r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"asn\")\r\n  |> group(columns: [\"Asn\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")"
    }
   ]
  },
  { "title": "Query List - Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Error [401, 403] (All Without Filter)",
   "type": "table",
   "description": "Query access denied, or without permission. No filter is applied; all queries from both public and private IPs are displayed.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r.Statuscode == \"401\" or r.Statuscode == \"403\")\r\n  |> filter(fn: (r) => r._field == \"uri\")\r\n  |> map(fn: (r) => ({ r with full: r.Domain + \" → \" + r._value }))\r\n  |> map(fn: (r) => ({ r with fulluri: r.Scheme + \"://\" + r.Domain + r._value }))\r\n  |> group(columns: [\"full\", \"Statuscode\", \"Ip\", \"fulluri\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"total\"})\r\n  |> map(fn: (r) => ({ r with open: \"Open\" }))\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n"
    }
   ]
  },
  {
   "title": "Only Status 404",
   "type": "table",
   "description": "Only shows queries with status code 404.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r.Statuscode == \"404\")\r\n  |> filter(fn: (r) => r._field == \"uri\")\r\n  |> map(fn: (r) => ({ r with full: r.Domain + \" → \" + r._value }))\r\n  |> map(fn: (r) => ({ r with fulluri: r.Scheme + \"://\" + r.Domain + r._value }))\r\n  |> group(columns: [\"full\", \"Ip\", \"fulluri\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"total\"})\r\n  |> map(fn: (r) => ({ r with open: \"Open\" }))\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n"
    }
   ]
  },
  {
   "title": "Only Status 500",
   "type": "table",
   "description": "Only shows queries with status code 500.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r.Statuscode == \"500\")\r\n  |> filter(fn: (r) => r._field == \"uri\")\r\n  |> map(fn: (r) => ({ r with full: r.Domain + \" → \" + r._value }))\r\n  |> map(fn: (r) => ({ r with fulluri: r.Scheme + \"://\" + r.Domain + r._value }))\r\n  |> group(columns: [\"full\", \"Ip\", \"fulluri\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"total\"})\r\n  |> map(fn: (r) => ({ r with open: \"Open\" }))\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n"
    }
   ]
  },
  {
   "title": "Any Queries",
   "type": "table",
   "description": "The status code doesn't matter; all queries are displayed.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r._field == \"uri\")\r\n  |> map(fn: (r) => ({ r with full: r.Domain + \" → \" + r._value }))\r\n  |> map(fn: (r) => ({ r with fulluri: r.Scheme + \"://\" + r.Domain + r._value }))\r\n  |> group(columns: [\"full\", \"Statuscode\",\"Ip\", \"fulluri\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"total\"})\r\n  |> map(fn: (r) => ({ r with open: \"Open\" }))\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n"
    }
   ]
  },
  {
   "title": "Any Queries Except Status [200, 401, 403, 404, 499, 500]",
   "type": "table",
   "description": "Show all queries where the status code is not 200, 404, 499 and 500.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] =~ /^${domainquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Domain\"] !~ /^${domainquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] =~ /^${ipquery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Ip\"] !~ /^${ipquery_exclude:regex}$/)\r\n  |> filter(fn: (r) => r[\"Statuscode\"] =~ /^${statuscodequery:regex}$/)\r\n  |> filter(fn: (r) => r[\"Agent\"] =~ /^${agentquery:regex}$/)\r\n  |> filter(fn: (r) => r.Statuscode != \"200\" and r.Statuscode != \"401\" and r.Statuscode != \"403\" and r.Statuscode != \"404\" and r.Statuscode != \"499\" and r.Statuscode != \"500\")\r\n  |> filter(fn: (r) => r._field == \"uri\")\r\n  |> map(fn: (r) => ({ r with full: r.Domain + \" → \" + r._value }))\r\n  |> map(fn: (r) => ({ r with fulluri: r.Scheme + \"://\" + r.Domain + r._value }))\r\n  |> group(columns: [\"full\", \"Statuscode\", \"Ip\", \"fulluri\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"total\"})\r\n  |> map(fn: (r) => ({ r with open: \"Open\" }))\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n"
    }
   ]
  },
  {
   "title": "All Accessed (with excluded IPs and internal calls)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Accessed Domains",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Detail overall (with excluded IPs and internal calls)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hits per IP",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 125 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "IP" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ip\")\r\n  |> group(columns: [\"Ip\"])\r\n  |> count()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"alias\")\r\n",
       "select": [
        [
         { "params": [ "IP" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hit's in the last ...",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 125 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"ip\")\r\n  |> group(columns: [\"_count\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
       "select": [
        [
         { "params": [ "IP" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hits per Nation",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 125 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"name\")\r\n  |> group(columns: [\"Name\"])\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n  |> count()",
       "select": [
        [
         { "params": [ "name" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hits per 1 min",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 131 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"domain\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"_time=1m\"])\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n  |> yield(name: \"count\")\r\n\r\n\r\n",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "alias" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Only excluded IPs Map",
     "type": "geomap",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "latitude" ], "type": "tag" },
        { "params": [ "longitude" ], "type": "tag" },
        { "params": [ "IP" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitoringRedirIPs\" or r[\"_measurement\"] == \"MonitoringRProxyIPs\")\r\n  |> filter(fn: (r) => r._field == \"ip\")  \r\n  |> group(columns: [\"Longitude\",\"Latitude\",\"Ip\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n\r\n",
       "select": [
        [
         { "params": [ "IP" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "counts" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Reverse Proxy - Monitoring and Internal Domain calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real Reverse Proxy Domains",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 152 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReverseProxyConnections\")\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Internal Reverse Proxy Domains",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"InternalRProxyIPs\")\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monitoring Reverse Proxy Domains",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MonitoringRProxyIPs\")\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Redirections - Monitoring and Internal Domain calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real Redirection Domains",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 173 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Internal Redirection Domains",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 186 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"InternalRedirIPs\")\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monitoring Redirection Domains",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 186 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "ReverseProxyConnections",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Redirections\")\r\n  |> filter(fn: (r) => r._field == \"domain\")\r\n  |> group(columns: [\"Domain\"])\r\n  |> count()\r\n  |> drop(columns: [\"host\", \"_field\", \"_measurement\", \"_start\", \"_stop\"])\r\n",
       "select": [
        [
         { "params": [ "Domain" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}